version: '3.7'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=gestao_ambiental
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: projeto_gestao_ambiental
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
